version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    environment:
      - SERVER_PORT=${BACKEND_PORT}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}